version: "3.8"

services:
  scraper:
    container_name: py_scraper
    build:
      context: .
    depends_on:
      - mysql_db
    restart: unless-stopped
    environment:
      DB_HOST: "mysql_db"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "root_test123"
    networks:
      - main

  mysql_db:
    container_name: mysql_db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root_test123"
      MYSQL_USER: "root_niet"
      MYSQL_PASSWORD: "woorden123"
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    networks:
      - main

networks:
  main:
