version: "3.8"

services:
  scraper:
    container_name: py_scraper
    build:
      context: .
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASSWORD: "root_test"
    networks:
      - main

  mysql:
    container_name: mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "root_test"
    ports:
      - "3306:3306"
    networks:
      - main

networks:
  main:
